word1=int(input("Type a number"))
word2=int(input("Type second number"))

print("Sum of ", word1,"and", word2, "is", word1+word2)
print("Difference of ", word1,"and", word2, "is", word1-word2)
print("product of", word1,"and", word2, "is", word1*word2)
print("floor division of ", word1,"and", word2, "is", word1//word2)
print("division of ", word1,"and", word2, "is", word1/word2)
print("Remainder of ", word1,"and", word2, "is", word1%word2)
print("3 to power of 4 is ", 3**4)